# Generated by Django 6.0.6 on 2026-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckstop_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('rack_id', models.IntegerField()),
                ('fuel_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='routing_fue_city_d8931a_idx'), models.Index(fields=['state'], name='routing_fue_state_a0c837_idx')],
            },
        ),
    ]
